spring:
  application:
    name: parking-fee-service
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_db
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    sql: debug
server:
  port: 8080
  error:
    include-message: always
